main: 
	g++ -g -std=c++0x -Wall sizeofdemo.cpp -o sizeof_demo
	g++ -g -std=c++0x -Wall two_dimension_find_demo.cpp -o two_dimension_find_demo
	g++ -g -std=c++0x -Wall replace_blank_demo.cpp -o replace_blank_demo

clean:
	rm sizeof_demo
	rm two_dimension_find_demo
	rm replace_blank_demo
