main: 
	g++ -g -std=c++0x -Wall two_dimension_find_demo.cpp -o two_dimension_find_demo
	g++ -g -std=c++0x -Wall replace_blank_demo.cpp -o replace_blank_demo
	g++ -g -std=c++0x -Wall sort_demo.cpp -o sort_demo 
	g++ -g -std=c++0x -Wall big_int_mul_demo.cpp -o big_int_mul_demo 
	g++ -g -std=c++0x -Wall 01_demo.cpp -o 01_demo
	g++ -g -std=c++0x -Wall 02_demo.cpp -o 02_demo

clean:
	rm two_dimension_find_demo
	rm replace_blank_demo
	rm sort_demo
	rm big_int_mul_demo
	rm 01_demo
	rm 02_demo
